library;

import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:newbug/core/helper/auth_helper.dart';
import 'package:newbug/core/network/model/home_cards_entity.dart';
import 'package:newbug/core/network/model/user_entity.dart';
import 'package:newbug/core/network/model/user_info.dart';
import 'package:newbug/core/widget/intro/flutter_intro.dart';
import 'package:newbug/page/chat/index.dart';
import 'package:newbug/page/guide/guide_view.dart';
import 'package:newbug/page/home/detail/flash_chat_view.dart';
import 'package:newbug/page/home/index/home_view.dart';
import 'package:newbug/page/home/unmatch/unmatch_view.dart';
import 'package:newbug/page/login/birth/index.dart';
import 'package:newbug/page/login/email/index.dart';
import 'package:newbug/page/login/gender/index.dart';
import 'package:newbug/page/login/interest/index.dart';
import 'package:newbug/page/login/launch/index.dart';
import 'package:newbug/page/login/login/index.dart';
import 'package:newbug/page/login/name/index.dart';
import 'package:newbug/page/login/photo/index.dart';
import 'package:newbug/page/login/sex/index.dart';
import 'package:newbug/page/main/main_view.dart';
import 'package:newbug/page/message/visitor/visitor_view.dart';
import 'package:newbug/page/profile/album/index/album_view.dart';
import 'package:newbug/page/profile/album/preview/preview_view.dart';
import 'package:newbug/page/profile/album/selected/selected_album_view.dart';
import 'package:newbug/page/profile/deleteAccount/delete_account_view.dart';
import 'package:newbug/page/profile/edit/edit_view.dart';
import 'package:newbug/page/profile/notification/index.dart';
import 'package:newbug/page/subscribe/subscribe_view.dart';
import 'package:newbug/page/web/web_view.dart';

part 'app_routes.dart';
part 'routes_manager.dart';
